config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root "static_pages#index"
  get "inquiry", to: "fotters#inquiry"
  get "terms", to: "fotters#terms"
  get "policy", to: "fotters#policy"
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'user/:id/posts', to: 'users#post', as: :user_posts
  get 'user/:id/like_posts', to: 'users#like_post' , as: :user_like_posts
  get "posts/search", to: 'posts#search'
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
  resources :line_bots, only: %i[new create]
  get "line_official" => "line_bots#official"
  post "line_bot/webhook" => "line_bots#webhook"
  resources :users do
    resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
  end
  resources :posts, shallow: true do
    resources :comments, only: %i[create destroy]
    resources :like_posts, only: %i[create destroy]
  end
  resources :password_resets, only: [:new, :create, :edit, :update]
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :require_login
  def index; end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/index.html.erb
<div class="container p-4">
  <div class="row">
    <div class="col-12 col-md-6">
      <%= image_tag "top_photo.png", class: "top_photo" %>
    </div>
    <div class="col-12 col-md-6 p-3 top_explanation">
      <div>
        <h1><strong>ぶさかわフォト</strong></h1>
        <p>ペットの｢ぶさかわ｣を投稿＆共有<br>普段見れないぶさかわなシーンで癒やされて見ませんか？</p>
        <div class="d-flex justify-content-evenly" >
          <%= link_to auth_at_provider_path(:provider => :line) do %>
            <%= image_tag "btn_login_hover.png" %>
          <% end %>
          <%= link_to "登録", new_user_path, class: "btn btn-outline-info" %>
          <%= link_to "ログイン", login_path, class: "btn btn-outline-info" %>
          <%= link_to "ゲスト", posts_path, class: "btn btn-outline-info" %>
        </div>
      </div>
    </div>
  </div>
  <h2 class="text-center mt-5"><strong>アプリでできること</strong></h2>
  <div class="row">
    <div class="col-12 col-md-6 p-3">
      <div class="card">
        <div class="card-body text-center">
          <h5 class="card-title m-3"><strong>ぶさかわな写真を投稿＆共有</strong></h5>
          <p><i class="bi bi-check"></i>ぶさかわなシーンを投稿<br><i class="bi bi-check"></i>コメントやいいね<br><i class="bi bi-check"></i>ランキング機能<br><i class="bi bi-check"></i>Xへの共有<br><i class="bi bi-check"></i>Instagramアカウント登録</p>
          <%= image_tag "top_photo_explanation1.gif", class: "top_photo_explanation p-3" %>
        </div>
      </div>
    </div>
    <div class="col-12 col-md-6 p-3">
      <div class="card">
        <div class="card-body text-center">
          <h5 class="card-title m-3"><strong>たくさんのぶさかわと出会える</strong></h5>
          <p><i class="bi bi-check"></i>公式LINEを友達登録すると通知を受け取る事ができます</p>
          <%= image_tag "top_photo_explanation2.png", class: "top_photo_explanation p-3" %>
        </div>
      </div>
    </div>
  </div>
</div>