config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root "static_pages#index"
  get "inquiry", to: "fotters#inquiry"
  get "terms", to: "fotters#terms"
  get "policy", to: "fotters#policy"
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'user/:id/posts', to: 'users#post', as: :user_posts
  get 'user/:id/like_posts', to: 'users#like_post' , as: :user_like_posts
  get "posts/search", to: 'posts#search'
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
  resources :line_bots, only: %i[new create]
  get "line_official" => "line_bots#official"
  post "line_bot/webhook" => "line_bots#webhook"
  resources :users do
    resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
  end
  resources :posts, shallow: true do
    resources :comments, only: %i[create destroy]
    resources :like_posts, only: %i[create destroy]
  end
  resources :password_resets, only: [:new, :create, :edit, :update]
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/like_post.rb
class LikePost < ApplicationRecord
  belongs_to :user
  belongs_to :post
  validates :user_id, uniqueness: { scope: :post_id }
end

app/controllers/like_posts_controller.rb
class LikePostsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @like_post = @post.like_posts.new(user_id: current_user.id)
    @like_post.save
  end

  def destroy
    @post = current_user.like_posts.find(params[:id]).post
    @like_post = current_user.like_posts.find(params[:id])
    @like_post.destroy
  end
end

app/helpers/like_posts_helper.rb
module LikePostsHelper
end

app/views/like_posts/_like_button.html.erb
<% if current_user.my_like_posts?(post) %>
  <%= link_to like_post_path(current_user.like_posts.find_by(post_id: post.id)), data: { turbo_method: "delete" } do %>
    <i class="bi bi-heart-fill"></i>
  <% end %> 
<% else %>
  <%= link_to post_like_posts_path(post), data: { turbo_method: "post" } do %>
    <i class="bi bi-heart"></i>
  <% end %> 
<% end %>

app/views/like_posts/_like_post.html.erb
<div id= "like_post-<%= post.id %>">
  <%= link_to like_post_path(current_user.like_posts.find_by(post_id: post.id)), data: { turbo_method: "delete" } do %>
    <i class="bi bi-heart-fill"></i>
  <% end %>
</div>

app/views/like_posts/_unlike_post.html.erb
<div id= "like_post-<%= post.id %>">
  <%= link_to post_like_posts_path(post), data: { turbo_method: "post" } do %>
    <i class="bi bi-heart"></i>
  <% end %> 
</div>

app/views/like_posts/create.turbo_stream.erb
<%= turbo_stream.replace "like_post-#{@post.id}" do %>
  <%= render 'like_posts/like_post', post: @post %>
<% end %>

app/views/like_posts/destroy.turbo_stream.erb
<%= turbo_stream.replace "like_post-#{@post.id}" do %>
  <%= render 'like_posts/unlike_post', post: @post %>
<% end %>