config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root "static_pages#index"
  get "inquiry", to: "fotters#inquiry"
  get "terms", to: "fotters#terms"
  get "policy", to: "fotters#policy"
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'user/:id/posts', to: 'users#post', as: :user_posts
  get 'user/:id/like_posts', to: 'users#like_post' , as: :user_like_posts
  get "posts/search", to: 'posts#search'
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
  resources :line_bots, only: %i[new create]
  get "line_official" => "line_bots#official"
  post "line_bot/webhook" => "line_bots#webhook"
  resources :users do
    resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
  end
  resources :posts, shallow: true do
    resources :comments, only: %i[create destroy]
    resources :like_posts, only: %i[create destroy]
  end
  resources :password_resets, only: [:new, :create, :edit, :update]
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true, confirmation: true, length: { minimum: 5, maximum: 40 }, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: 'は英数字の混合である必要があります' }, if: lambda {
    new_record? || changes[:crypted_password]
  } 
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }
  validates :reset_password_token, uniqueness: true, allow_nil: true
  validates :instagram_account_url, allow_blank: true, format: { with: %r{\Ahttps://(?:www\.)?instagram\.com/[a-zA-Z0-9._%+-]+(=[^&]*)?(\?.+)?\z} }
  validates :line_user_id, uniqueness: true, allow_nil: true

  mount_uploader :avatar, UserAvatarUploader
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :like_posts, dependent: :destroy
  has_many :my_like_posts, through: :like_posts, source: :post
  has_many :post_counts, dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :authentications, dependent: :destroy
  accepts_nested_attributes_for :authentications

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def my_like_posts?(post)
    my_like_posts.include?(post)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  before_action :set_user, only: %i[show edit update destroy]
  def show; end

  def new
    @user = User.new
  end

  def edit; end

  def create
    @user = User.new(params_user)
    if @user.save
      auto_login(@user)
      flash[:notice] = "アカウント作成しました"
      redirect_to line_official_path
    else
      flash.now[:alert] ="アカウント作成に失敗しました"
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @user.update(params_user)
      flash[:notice] = "ユーザー情報を更新しました"
      redirect_to user_path
    else
      flash.now[:alert] ="ユーザー情報の更新に失敗しました"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy!
    flash[:alert] = "アカウントを削除しました"
    redirect_to root_path
  end

  def post
    @posts = current_user.posts.order("created_at DESC").page(params[:page])
  end

  def like_post
    @posts = current_user.my_like_posts.includes(:user).order("like_posts.created_at DESC").page(params[:page])
  end

  private

  def params_user
    params.require(:user).permit(:name, :email, :instagram_account_url, :password, :password_confirmation, :avatar, :avatar_cache)
  end

  def set_user
    @user = User.find(current_user.id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  <div class="edit_account">
    <h1 class="text-center p-3 m-3">アカウント編集</h1>
    <%= form_with model: @user do |form| %>
      <%= render 'shared/error_messages', object: form.object %>
      <%= form.label :name, class: "form-label" %>
      <%= form.text_field :name, class: "form-control" %>
    
      <%= form.label :instagram_account_url, class: "form-label" %>
      <%= form.text_field :instagram_account_url, class: "form-control" %>
    
      <%= form.label :avatar, class: "form-label" %>
      <%= form.file_field :avatar, class: "form-control" %>
      <%= form.hidden_field :avatar_cache %>
    
      <%= image_tag @user.avatar.url, size: '100x100', class: "mx-auto d-block" %>
    
      <%= form.submit "編集", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/like_post.html.erb
<div class="container">
  <div class="user_like_posts">
    <h1 class="text-center p-3 m-3">いいね投稿一覧</h1>
    <div class="row justify-content-center">
      <% @posts.each do |post| %>
        <div class="col-xs-12 col-md-3 border border-info text-center m-2">
          <%= link_to post_path(post), class: "post_show" do %>
            <%= image_tag post.images[0].url, size: '250x250' %>
            <div class="title">
              <%= post.title %>
            </div>
          <% end %>
          <div class="user">
            <%= post.user.name %>
            <%= image_tag post.user.avatar.url, class: "rounded-circle",size: '50x50' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<%= paginate @posts %>

app/views/users/new.html.erb
<div class="container">
  <div class= "new_account">
    <h1 class= "text-center p-3 m-3">アカウント作成</h1>
      <%= form_with model: @user do |form| %>
        <%= render 'shared/error_messages', object: form.object %>
        <%= form.label :name, class: "form-label" %>
        <%= form.text_field :name, class: "form-control" %>

        <%= form.label :email, class: "form-label" %>
        <%= form.text_field :email, class: "form-control" %>

        <%= form.label :avatar, class: "form-label" %>
        <%= form.file_field :avatar, class: "form-control" %>
        <%= form.hidden_field :avatar_cache %>

        <%= form.label :instagram_account_url, class: "form-label" %>
        <%= form.text_field :instagram_account_url, class: "form-control" %>

        <%= form.label :password, class: "form-label" %>
        <%= form.password_field :password, class: "form-control" %>

        <%= form.label :password_confirmation, class: "form-label" %>
        <%= form.password_field :password_confirmation, class: "form-control" %>

        <%= form.submit "送信", class: "btn btn-primary" %>
      <% end %>
  </div>
</div>

app/views/users/post.html.erb
<div class="container">
  <div class="user_posts">
    <h1 class="text-center p-3 m-3">投稿一覧</h1>
    <div class="row justify-content-center">
      <% @posts.each do |post| %>
        <div class="col-xs-12 col-md-3 border border-info text-center m-2">
          <%= link_to post_path(post), class: "post_show" do %>
            <%= image_tag post.images[0].url, size: '250x250' %>
            <div class="title">
              <%= post.title %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<%= paginate @posts %>

app/views/users/show.html.erb
<div class= "container">
  <div class="d-flex justify-content-center align-items-center">
    <div class="card" style="width: 18rem;">
      <%= image_tag @user.avatar.url, size: '200x200', class: "mx-auto d-block p-3 m-4" %>
      <ul class="list-group list-group-flush">
        <li class="list-group-item"><%= @user.name %></li>
        <% if @user.instagram_account_url.present? %>
          <li class="list-group-item">
            <%= image_tag "Instagram_Glyph_Gradient.png", size: '40x40' %>
          </li>
        <% end %>
        <li class="list-group-item"><%= link_to "アカウント情報変更はこちら", edit_user_path %></li>
      </ul>
    </div>
  </div>
</div>