config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  root "static_pages#index"
  get "inquiry", to: "fotters#inquiry"
  get "terms", to: "fotters#terms"
  get "policy", to: "fotters#policy"
  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy'
  get 'user/:id/posts', to: 'users#post', as: :user_posts
  get 'user/:id/like_posts', to: 'users#like_post' , as: :user_like_posts
  get "posts/search", to: 'posts#search'
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback"
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
  resources :line_bots, only: %i[new create]
  get "line_official" => "line_bots#official"
  post "line_bot/webhook" => "line_bots#webhook"
  resources :users do
    resource :relationships, only: [:create, :destroy]
      get "followings" => "relationships#followings", as: "followings"
  end
  resources :posts, shallow: true do
    resources :comments, only: %i[create destroy]
    resources :like_posts, only: %i[create destroy]
  end
  resources :password_resets, only: [:new, :create, :edit, :update]
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
  
  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <% object.errors.full_messages.each do |msg| %>
    <%= msg %>
  <% end %>
<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <p class="alert alert-success"><%= notice %></p>
<% elsif flash[:alert] %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/shared/_header_login.html.erb
<nav class="navbar navbar-expand-lg">
  <div class="container-fluid">
    <%= link_to posts_path, class: "navbar-brand" do %>
      <%= image_tag "profile.png", class: "header_icon" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "投稿", new_post_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= search_form_for @q, url: posts_path, class: "d-flex" do |form| %>
            <div data-controller="autocomplete" data-autocomplete-url-value="/posts/search" role="combobox">
              <%= form.search_field :title_cont, class: "form-control me-2", data: { autocomplete_target: 'input' } %>
              <ul class="list-group" data-autocomplete-target="results"></ul>
            </div>
            <%= form.submit '検索', class: "btn btn-outline-success" %>
          <% end %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            ユーザー情報
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to "プロフィール", user_path(current_user), class: "dropdown-item" %></li>
            <li><%= link_to "公式LINE", line_official_path, class: "dropdown-item" %></li>
            <li><%= link_to "パスワード変更", new_password_reset_path, class: "dropdown-item" %></li>
            <li><%= link_to "投稿一覧", user_posts_path(current_user), class: "dropdown-item" %></li>
            <li><%= link_to "いいね一覧", user_like_posts_path(current_user), class: "dropdown-item" %></li>
            <li><%= link_to "フォロー一覧", user_followings_path(current_user), class: "dropdown-item" %></li>
            <li><%= link_to "ログアウト", logout_path, data: { turbo_method: :delete, turbo_confirm: "ログアウトしますか？" }, class: "dropdown-item" %></li>
            <li><%= link_to "アカウント削除", user_path(current_user.id), data: { turbo_method: :delete, turbo_confirm: "削除しますか？" }, class: "dropdown-item" %><li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>